export const EVENT_CATEGORIES = [
  "Tech and Innovation",
  "Business and Entrepreneurship",
  "Arts and Culture",
  "Science and Research",
  "Education and Learning",
  "Health and Wellness",
  "Sports and Fitness",
  "Social Impact",
  "Entertainment",
  "Professional Development",
  "Networking",
  "Workshops and Training",
  "Conferences and Summits",
  "Hackathons",
  "Competitions",
  "Exhibitions",
  "Seminars",
  "Webinars",
  "Meetups",
  "Other"
];

export const EVENT_TAGS = [
  "Workshops",
  "Conferences",
  "Networking",
  "Learning",
  "Innovation",
  "Technology",
  "Business",
  "Startup",
  "Career",
  "Skills",
  "Leadership",
  "Creative",
  "Social",
  "Professional",
  "Community",
  "Research",
  "Development",
  "Design",
  "Marketing",
  "Finance",
  "Healthcare",
  "Education",
  "Environment",
  "Sustainability",
  "Diversity",
  "Inclusion",
  "Youth",
  "Students",
  "Entrepreneurs",
  "Professionals",
  "Remote",
  "Online",
  "In-Person",
  "Hybrid"
];
